---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by root.
--- DateTime: 19-7-11 上午10:17
---

local DB = require("app.libs.mysql_db")
local cf = require("app.config.cf_database")
local cjson = require("cjson")

local db = DB:new(cf.mysql)

local user_model = {}

function user_model:query_by_name (username,password)
    ngx.log(ngx.err,"***********"..username.."***"..password)

    local res,err = db:query("select *  from t_user where name = ? and password = ? limit 1",
            {username,password})

    if not res or err or type(res) ~= "table" then
        return nil, err or "error"
    end

    if #res > 0 then
        return res[1]
    end


    return nil

end

function user_model:add_user (user)

    --ngx.say(user["name"])
    local uid,err = db:insert("insert into user (name,password,age,address) values (?,?,?,?)",
            {user.name,user.pwd,user.age,user.address})
    if err then
        return nil,err
    end
    return uid,nil

end



return user_model