---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by root.
--- DateTime: 19-7-15 下午1:22
---

local lor = require("lor.index")
local about_user_rou = lor:Router()
local user_modul = require("app.model.user_model")
local utils_model = require "app.model.utils_model"
local public_con = require "app.config.public"

about_user_rou:post("/create", function(req, res, next)

    local body = req.body
    --local name = body.name

    local user = {
        name = body.name,
        pwd = body.pwd,
        age = body.age,
        address = body.address
    }

    local uid,err = user_modul:add_user(user)

    if err then
        return res:json(public_con['error']['account_exist_error'])
    end

    local info = {}
    info.uid = uid

    local data = utils_model:table_clone(public_con['success'])
    data.info = info

    return res:json(data)


end)

return about_user_rou