---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by root.
--- DateTime: 19-7-15 上午10:31
---多级函数处理

local lor = require("lor.index")

local anyFunRouter = lor:Router()

--路由不能放在函数前

local func1 = function(req, res, next)
    ngx.say("this is func1")
    local num = tonumber(req.params.num)

    ngx.say("this is func1 , num = ",num+1)
    next()
end

local func2 = function(req, res, next)

--[[    local num = tonumber(req.params.num)

    ngx.say("this is func2 , num = ",num/2)]]
    next()
end

local func3 = function(req, res, next)

--[[    local num = tonumber(req.params.num)

    ngx.say("this is func3 , num = ",num*2)]]

end

anyFunRouter:get("/test",{func1,func2,func3})

return anyFunRouter